In [1]:
# Import dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

In [ ]:
# Import dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

In [2]:
#  Read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [5]:
# Drop columns that we don't need
application_df = application_df.drop(["EIN","NAME"],axis=1)

In [60]:
# find unique values
application_df.nunique()

APPLICATION_TYPE             9
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [13]:
# Make the class_counts variable if it doesn't exist
if 'class_counts' not in globals():
    # Create a dictionary of class counts
    class_counts = application_df['APPLICATION_TYPE'].value_counts().to_dict()

# Filter class_counts for values greater than 1
filtered_class_counts = {key: value for key, value in class_counts.items() if value > 1}

# Print the filtered class counts
print(filtered_class_counts)

{'T3': 27037, 'T4': 1542, 'T6': 1216, 'T5': 1173, 'T19': 1065, 'T8': 737, 'T7': 725, 'T10': 528, 'T9': 156, 'T13': 66, 'T12': 27, 'T2': 16, 'T25': 3, 'T14': 3, 'T29': 2, 'T15': 2}

In [9]:
# Bin APPLICATION_TYPE value counts
application_counts = application_df['APPLICATION_TYPE'].value_counts()
application_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [10]:
# Bin APPLICATION_TYPE value counts
application_counts = application_df['APPLICATION_TYPE'].value_counts()
application_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [14]:
application_types_to_replace = list(application_counts[application_counts < 500].index)

In [50]:
print("Values to be replaced with 'Other':", application_types_to_replace)

Values to be replaced with 'Other': ['T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17']

In [15]:
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

In [16]:
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

In [51]:
# Before replacement
print("Before replacement:")
print(application_df['APPLICATION_TYPE'].value_counts())

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app, "Other")

# After replacement
print("After replacement:")
print(application_df['APPLICATION_TYPE'].value_counts())

Before replacement:
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64
After replacement:
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [17]:
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

In [22]:
class_counts_series = pd.Series(class_counts)
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [52]:
# Calculate class counts
class_counts = application_df['CLASSIFICATION'].value_counts()

# Print keys and values
print("Keys:", class_counts.keys())
print("Values:", class_counts.values)

Keys: Index(['C1000', 'C2000', 'C1200', 'C3000', 'C2100', 'C7000', 'C1700', 'C4000',
       'C5000', 'C1270', 'C2700', 'C2800', 'C7100', 'C1300', 'C1280', 'C1230',
       'C1400', 'C7200', 'C2300', 'C1240', 'C8000', 'C7120', 'C1500', 'C1800',
       'C6000', 'C1250', 'C8200', 'C1238', 'C1278', 'C1235', 'C1237', 'C7210',
       'C2400', 'C1720', 'C4100', 'C1257', 'C1600', 'C1260', 'C2710', 'C0',
       'C3200', 'C1234', 'C1246', 'C1267', 'C1256', 'C2190', 'C4200', 'C2600',
       'C5200', 'C1370', 'C1248', 'C6100', 'C1820', 'C1900', 'C1236', 'C3700',
       'C2570', 'C1580', 'C1245', 'C2500', 'C1570', 'C1283', 'C2380', 'C1732',
       'C1728', 'C2170', 'C4120', 'C8210', 'C2561', 'C4500', 'C2150'],
      dtype='object')
Values: [17326  6074  4837  1918  1883   777   287   194   116   114   104    95
    75    58    50    36    34    32    32    30    20    18    16    15
    15    14    11    10    10     9     9     7     6     6     6     5
     5     3     3     3     2     2     2     2     2     1     1     1
     1     1     1     1     1     1     1     1     1     1     1     1
     1     1     1     1     1     1     1     1     1     1     1]

In [54]:
# Split the preprocessed data into features and target arrays
X = application_with_dummies_df.drop(["IS_SUCCESSFUL"], axis=1).values
y = application_with_dummies_df["IS_SUCCESSFUL"].values

# Split the data into training and testing datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [55]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the training and testing data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [56]:
# Define the model - deep neural net
number_input_features = len(X_train[0])
hidden_nodes_layer1 = 80
hidden_nodes_layer2 = 30

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                8720

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 11181 (43.68 KB)
Trainable params: 11181 (43.68 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [57]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [58]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 4s 3ms/step - loss: 0.5734 - accuracy: 0.7218
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5529 - accuracy: 0.7314
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5496 - accuracy: 0.7308
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5472 - accuracy: 0.7346
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5466 - accuracy: 0.7336
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5446 - accuracy: 0.7347
Epoch 7/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5435 - accuracy: 0.7350
Epoch 8/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5427 - accuracy: 0.7360
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7357
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7373
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7356
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5402 - accuracy: 0.7379
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7387
Epoch 14/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5397 - accuracy: 0.7376
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5387 - accuracy: 0.7385
Epoch 16/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5389 - accuracy: 0.7383
Epoch 17/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5386 - accuracy: 0.7390
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5381 - accuracy: 0.7393
Epoch 19/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5377 - accuracy: 0.7385
Epoch 20/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5374 - accuracy: 0.7392
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5368 - accuracy: 0.7397
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5370 - accuracy: 0.7393
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5365 - accuracy: 0.7392
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5367 - accuracy: 0.7395
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5362 - accuracy: 0.7399
Epoch 26/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5355 - accuracy: 0.7399
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5358 - accuracy: 0.7400
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5354 - accuracy: 0.7400
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5356 - accuracy: 0.7404
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5352 - accuracy: 0.7409
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5346 - accuracy: 0.7413
Epoch 32/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5343 - accuracy: 0.7411
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5349 - accuracy: 0.7407
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5344 - accuracy: 0.7405
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5341 - accuracy: 0.7413
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5338 - accuracy: 0.7415
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5341 - accuracy: 0.7407
Epoch 38/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5338 - accuracy: 0.7406
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5334 - accuracy: 0.7414
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7406
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5342 - accuracy: 0.7417
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5329 - accuracy: 0.7419
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5332 - accuracy: 0.7420
Epoch 44/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5327 - accuracy: 0.7414
Epoch 45/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5330 - accuracy: 0.7416
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5323 - accuracy: 0.7429
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5325 - accuracy: 0.7421
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5327 - accuracy: 0.7418
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5323 - accuracy: 0.7431
Epoch 50/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5321 - accuracy: 0.7424
Epoch 51/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5320 - accuracy: 0.7414
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5318 - accuracy: 0.7411
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5324 - accuracy: 0.7432
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5319 - accuracy: 0.7432
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5317 - accuracy: 0.7427
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5309 - accuracy: 0.7417
Epoch 57/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5315 - accuracy: 0.7424
Epoch 58/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5315 - accuracy: 0.7434
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5315 - accuracy: 0.7423
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5311 - accuracy: 0.7423
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5312 - accuracy: 0.7432
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5308 - accuracy: 0.7414
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5308 - accuracy: 0.7419
Epoch 64/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5308 - accuracy: 0.7430
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5306 - accuracy: 0.7427
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5305 - accuracy: 0.7426
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5304 - accuracy: 0.7429
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5302 - accuracy: 0.7436
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5303 - accuracy: 0.7437
Epoch 70/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5305 - accuracy: 0.7429
Epoch 71/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5303 - accuracy: 0.7428
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5303 - accuracy: 0.7428
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5302 - accuracy: 0.7430
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5299 - accuracy: 0.7428
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5299 - accuracy: 0.7425
Epoch 76/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5300 - accuracy: 0.7426
Epoch 77/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5297 - accuracy: 0.7432
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5297 - accuracy: 0.7421
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5298 - accuracy: 0.7429
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5297 - accuracy: 0.7432
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5297 - accuracy: 0.7416
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5300 - accuracy: 0.7434
Epoch 83/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5294 - accuracy: 0.7425
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5292 - accuracy: 0.7422
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5294 - accuracy: 0.7431
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5296 - accuracy: 0.7439
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5290 - accuracy: 0.7438
Epoch 88/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5292 - accuracy: 0.7427
Epoch 89/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5293 - accuracy: 0.7436
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5291 - accuracy: 0.7429
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5287 - accuracy: 0.7435
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5295 - accuracy: 0.7432
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5291 - accuracy: 0.7431
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5290 - accuracy: 0.7438
Epoch 95/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5290 - accuracy: 0.7425
Epoch 96/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5292 - accuracy: 0.7439
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5287 - accuracy: 0.7446
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5285 - accuracy: 0.7432
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5285 - accuracy: 0.7444
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5284 - accuracy: 0.7436

In [59]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Print the model's loss and accuracy
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 2s - loss: 0.5647 - accuracy: 0.7261 - 2s/epoch - 8ms/step
Loss: 0.5646594762802124, Accuracy: 0.726064145565033

In [61]:
# Export the model to an HDF5 file
nn.save("AlphabetSoupCharity.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(